### ISSUE TITLE
Flask bug

### ISSUE THREAD

**Issue by cornradio** [NisheetNakrani/NOTE-IT-APP#14]
```
py .\main.py
Traceback (most recent call last):
  File "C:\Users\kasus\Documents\GitHub\NOTE-IT-APP\main.py", line 1, in <module>
    from website import create_app
  File "C:\Users\kasus\Documents\GitHub\NOTE-IT-APP\website\__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
```
may need install specify version of Flask? pls help!

**Comment by cornradio** [comment]
i already install everything in requirements.txt

**Comment by cornradio** [comment]
oh i figure out that , but have a new problem
```
PS C:\Users\kasus\Documents\GitHub\NOTE-IT-APP> py .\main.py
Traceback (most recent call last):
  File "C:\Users\kasus\Documents\GitHub\NOTE-IT-APP\main.py", line 1, in <module>
    from website import create_app
  File "C:\Users\kasus\Documents\GitHub\NOTE-IT-APP\website\__init__.py", line 1, in <module>
    from flask import Flask
  File "C:\Users\kasus\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "C:\Users\kasus\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 28, in <module>
    from . import cli
  File "C:\Users\kasus\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "C:\Users\kasus\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (C:\Users\kasus\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\urls.py)
```

**Comment by cornradio** [comment]
tried to create a venv for this proj still get that error 
```
(venv) PS C:\Users\kasus\Documents\GitHub\NOTE-IT-APP> py .\main.py
Traceback (most recent call last):
  File "C:\Users\kasus\Documents\GitHub\NOTE-IT-APP\main.py", line 1, in <module>
    from website import create_app
  File "C:\Users\kasus\Documents\GitHub\NOTE-IT-APP\website\__init__.py", line 1, in <module>
    from flask import Flask
  File "C:\Users\kasus\Documents\GitHub\NOTE-IT-APP\venv\lib\site-packages\flask\__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "C:\Users\kasus\Documents\GitHub\NOTE-IT-APP\venv\lib\site-packages\flask\app.py", line 28, in <module>
    from . import cli
  File "C:\Users\kasus\Documents\GitHub\NOTE-IT-APP\venv\lib\site-packages\flask\cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "C:\Users\kasus\Documents\GitHub\NOTE-IT-APP\venv\lib\site-packages\flask\helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (C:\Users\kasus\Documents\GitHub\NOTE-IT-APP\venv\lib\site-packages\werkzeug\urls.py)
```

**Comment by Bijay-Prasad** [comment]
I had the same problem. It is because `Werkzeug 3.0.0` was released and Flask doesn't specify the dependency correctly (requirements say Werkzeug>=2.2.0). This is why, Werkzeug 3.0.0 is still installed and Flask 2.2.2 isn't made for Werkzeug 3.0.0.

**Solution:** Replace `werkzeug==2.2.2` with previous version in your `requirements.txt` And again try to install all modules using `pip install -r requirements.txt.` Run your web app using `python main.py`. I hope this will work for you as well.
https://werkzeug.palletsprojects.com/en/3.0.x/changes/#version-3-0-0
